import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :te_phoenix, TePhoenixWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# force_ssl is compile-time in Plug.SSL, so it can't be flipped via a
# runtime env var here. We leave it OFF in the compiled config and let
# the operator terminate TLS at the reverse-proxy layer when certs are
# actually present. This avoids the infinite-redirect trap on a plain-
# HTTP deploy where Plug.SSL redirects HTTP → HTTPS → HTTP → …
#
# To re-enable for a TLS-fronted deploy:
#
#     config :te_phoenix, TePhoenixWeb.Endpoint,
#       force_ssl: [
#         rewrite_on: [:x_forwarded_proto],
#         exclude: [hosts: ["localhost", "127.0.0.1"]]
#       ]

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
