defmodule TePhoenixWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :te_phoenix

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_te_phoenix_key",
    signing_salt: "PEA7Gd6N",
    same_site: "Lax"
  ]

  socket "/socket", TePhoenixWeb.UserSocket,
    websocket: true,
    longpoll: false

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :te_phoenix,
    gzip: not code_reloading?,
    only: TePhoenixWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :te_phoenix
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug :parse_body

  defp parse_body(conn, _opts) do
    Plug.Parsers.call(conn,
      Plug.Parsers.init(parsers: [:urlencoded, :multipart, :json], pass: ["*/*"], json_decoder: Phoenix.json_library())
    )
  rescue
    Plug.Parsers.ParseError ->
      conn
      |> Plug.Conn.put_resp_content_type("application/json")
      |> Plug.Conn.send_resp(400, Jason.encode!(%{success: false, message: "Invalid request body."}))
      |> Plug.Conn.halt()
  end

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug TePhoenixWeb.Router
end
